#!/bin/bash

# albert
function install_albert {
  sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_19.04/ /' > /etc/apt/sources.list.d/home:manuelschneid3r.list"
  wget -nv https://download.opensuse.org/repositories/home:manuelschneid3r/xUbuntu_19.04/Release.key -O Release.key
  sudo apt-key add - < Release.key
  sudo apt-get update
  sudo apt-get install albert -y
  whiptail --title "Finished" --msgbox "Installation of Albert for Ubuntu 18.04 complete." 8 56
  install_thirdparty
}
