#!/bin/bash

# Commandbox
function install_commandbox {
	sudo apt install libappindicator-dev openjdk-11-jre -y
	curl -fsSl https://downloads.ortussolutions.com/debs/gpg | sudo apt-key add -
	echo "deb https://downloads.ortussolutions.com/debs/noarch /" | sudo tee -a /etc/apt/sources.list.d/commandbox.list
	sudo apt-get update -y && sudo apt-get install apt-transport-https commandbox -y
	box install commandbox-cfformat
	whiptail --title "Finished" --msgbox "Installation of Commandbox complete." 8 56
	install_thirdparty
}
