#!/bin/bash

# Commandbox
function install_commandbox {
	superuser_do "apt install libappindicator-dev openjdk-11-jre -y"
	curl -fsSl https://downloads.ortussolutions.com/debs/gpg | sudo apt-key add -
	echo "deb https://downloads.ortussolutions.com/debs/noarch /" | sudo tee -a /etc/apt/sources.list.d/commandbox.list
	superuser_do "apt update -y -qq"
  superuser_do "apt install apt-transport-https commandbox -y"
	box install commandbox-cfformat
	box install cfml-compiler
	whiptail --title "Finished" --msgbox "Installation of Commandbox complete." 8 56
	install_thirdparty
}
