#!/bin/bash

# dbeaver
function install_dbeaver {
	wget -O - https://dbeaver.io/debs/dbeaver.gpg.key | sudo apt-key add -
	echo "deb https://dbeaver.io/debs/dbeaver-ce /" | sudo tee /etc/apt/sources.list.d/dbeaver.list	
	sudo apt update
	sudo apt install dbeaver-ce -y
	whiptail --title "Finished" --msgbox "Installation of dbeaver complete." 8 56
	install_thirdparty
}
