#!/bin/bash

# Elementary Tweaks
function install_elementary_tweaks {
  NAME="Elementary Tweaks"
	PACKAGE="elementary-tweaks"
	PPA="philip.scott/elementary-tweaks"
	add_launchpad_ppa "$NAME" "$PPA" install_thirdparty
	if [ $? = 0 ]; then
		install_package "$NAME" "$PACKAGE" install_thirdparty
	else
		echo_message info "Installation of $NAME cancelled."
		install_thirdparty
	fi
}
