#!/bin/bash

# Github Desktop
function install_github_desktop {
	wget -qO - https://packagecloud.io/shiftkey/desktop/gpgkey | sudo apt-key add -
	sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/shiftkey/desktop/any/ any main" > /etc/apt/sources.list.d/packagecloud-shiftky-desktop.list'
	superuser_do "apt update -y -qq"
	superuser_do "apt install github-desktop"
	whiptail --title "Finished" --msgbox "Installation of GitHub Desktop complete." 8 56
	install_thirdparty
}
