#!/bin/bash

# Localstack
function install_localstack {
	pip3 install localstack
	pip3 install awscli-local
	whiptail --title "Finished" --msgbox "Installation of Localstack complete." 8 56
	install_thirdparty
}
