#!/bin/bash

# opera
function install_opera {
	wget -qO- https://deb.opera.com/archive.key | superuser_do "apt-key add -"
	sudo add-apt-repository "deb [arch=i386,amd64] https://deb.opera.com/opera-stable/ stable non-free"
	superuser_do "apt install opera-stable -y"
	install_thirdparty
}
