#!/bin/bash

# Elementary Tweaks
function install_pantheon_terminal {
  NAME="Pantheon Terminal"
	PACKAGE="pantheon-terminal"
	PPA="elementary-os/stable"
	add_launchpad_ppa "$NAME" "$PPA" install_thirdparty
	if [ $? = 0 ]; then
		install_package "$NAME" "$PACKAGE" install_thirdparty
	else
		echo_message info "Installation of $NAME cancelled."
		install_thirdparty
	fi
}
