#!/bin/bash

# Virtualbox
function install_virtualbox {
	wget https://download.virtualbox.org/virtualbox/5.2.36/virtualbox-5.2_5.2.36-135684~Ubuntu~bionic_amd64.deb virtualbox.deb
	sudo dpkg --install virtualbox.deb
	rm virtualbox.deb
	whiptail --title "Finished" --msgbox "Installation of Virtualbox complete." 8 56
	install_thirdparty
}
