#!/bin/bash

# Visual Studio Code
function install_vscode {
	PACKAGE=~/Downloads/vscode.deb
	if [ ! -f ${PACKAGE} ]; then
		wget https://go.microsoft.com/fwlink/?LinkID=760868 -O ${PACKAGE}
	fi
	superuser_do "apt install ${PACKAGE}"
	code --install-extension Shan.code-settings-sync
	whiptail --title "Finished" --msgbox "Installation of Visual Studio Code complete." 8 56
	install_thirdparty
}
